(()=>{'use strict';
const $=s=>document.querySelector(s),shell=$('[data-staff-shell]'),work=$('[data-workspace]'),status=$('[data-status]'),modal=$('[data-modal]'),toast=$('[data-toast]');
const factionNames={dokains:'Докаины',frauster:'Фраустер',maizervin:'Майзервин',paladins:'Паладины',doronto:'Культ Доронто'},ranks=['0','I','II','III','IV','V'];
let account,isFullAdmin=false,canGrantStaff=false,query='',offset=0,users=[],selected=null,detail=null,currentSection='users',currentTab='profile',auditFilter='ALL',lastFocus=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=e=>window.TODMAuth?.message(e)||e?.message||'Неизвестная ошибка';
const say=t=>status.textContent=t;
const notify=t=>{toast.textContent=t;toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.hidden=true,4200)};
const avatar=u=>u.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(u.display_name||u.email||'TODM')}&backgroundColor=11100e&fontFamily=Georgia`;
const loading=()=>work.innerHTML='<div class="staff-skeleton"></div><div class="staff-skeleton"></div><div class="staff-skeleton"></div>';
const openPanel=()=>{lastFocus=document.activeElement;shell.hidden=false;document.body.style.overflow='hidden';renderSection(currentSection);setTimeout(()=>work.focus(),0)};
const closePanel=()=>{shell.hidden=true;document.body.style.overflow='';lastFocus?.focus()};
const openModal=({title,body,confirm='Подтвердить',danger=false,onConfirm})=>{modal.innerHTML=`<form class="staff-modal-card"><p class="eyebrow">Требуется подтверждение</p><h3>${esc(title)}</h3>${body}<div class="staff-modal-actions"><button class="staff-action" type="button" data-cancel>Отмена</button><button class="staff-action ${danger?'danger':'primary'}" type="submit">${esc(confirm)}</button></div></form>`;modal.hidden=false;const form=modal.querySelector('form');form.querySelector('[data-cancel]').onclick=()=>modal.hidden=true;form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await onConfirm(new FormData(form));modal.hidden=true}catch(err){notify(`Ошибка: ${msg(err)}`)}finally{submit.disabled=false}};setTimeout(()=>form.querySelector('textarea,input,button')?.focus(),0)};
const closeModal=()=>{modal.hidden=true};
document.querySelector('[data-open-panel]').onclick=openPanel;document.querySelectorAll('[data-close-panel]').forEach(b=>b.onclick=closePanel);
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===b));currentSection=b.dataset.section;selected=null;renderSection(currentSection)});
addEventListener('keydown',e=>{if(e.key==='Escape'){if(!modal.hidden)closeModal();else if(!shell.hidden)closePanel()}if(e.key==='Tab'&&!modal.hidden){const f=[...modal.querySelectorAll('button,input,textarea,select')].filter(x=>!x.disabled);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});

async function loadUsers(){loading();const r=await TODMAuth.client.rpc('admin_list_users',{p_search:query,p_offset:offset});if(r.error)throw r.error;users=r.data||[];const ids=users.map(x=>x.user_id),[restrictions,avatars,profiles]=await Promise.all([TODMAuth.client.rpc('admin_chat_restrictions',{p_user_ids:ids}),TODMAuth.client.rpc('admin_avatar_states',{p_user_ids:ids}),TODMAuth.client.rpc('social_profiles',{p_user_ids:ids})]);if(restrictions.error||avatars.error||profiles.error)throw restrictions.error||avatars.error||profiles.error;const extra={};[...(restrictions.data||[]),...(avatars.data||[]),...(profiles.data||[])].forEach(x=>Object.assign(extra[x.user_id]||(extra[x.user_id]={}),x));users.forEach(x=>Object.assign(x,extra[x.user_id]||{}));renderUsers()}
function renderUsers(){work.innerHTML=`<div class="staff-title-row"><div><p class="eyebrow">Личные дела</p><h3>Пользователи</h3></div><form class="staff-search"><input name="q" value="${esc(query)}" maxlength="100" placeholder="Почта или ник" aria-label="Поиск пользователей"><button>Найти</button></form></div><div class="staff-user-list">${users.length?users.map(u=>`<button class="staff-user-row" data-user="${u.user_id}"><img class="staff-avatar" src="${esc(avatar(u))}" alt=""><span><span class="staff-user-name">${esc(u.display_name||'Без ника')}</span><span class="staff-user-meta">${esc(u.email)}</span></span><span class="staff-pill">Архив ${ranks[Math.min(+u.archive_level||0,5)]}</span><span class="staff-pill">${esc(factionNames[u.selected_faction]||'Без фракции')}</span></button>`).join(''):'<p class="staff-empty">Пользователи не найдены.</p>'}</div><div class="staff-pagination"><button class="staff-action" data-prev ${offset?'':'disabled'}>← Назад</button><span>Страница ${offset/50+1}</span><button class="staff-action" data-next ${users.length<50?'disabled':''}>Далее →</button></div>`;work.querySelector('form').onsubmit=e=>{e.preventDefault();query=new FormData(e.currentTarget).get('q').trim();offset=0;loadUsers().catch(fail)};work.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>openUser(b.dataset.user));work.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-50);loadUsers().catch(fail)};work.querySelector('[data-next]').onclick=()=>{offset+=50;loadUsers().catch(fail)}}
async function openUser(id,tab='profile'){selected=id;currentTab=tab;loading();const r=await TODMAuth.client.rpc('archive_staff_user_detail',{p_user_id:id,p_ledger_limit:40});if(r.error)throw r.error;detail=r.data;renderUser()}
function renderUser(){const p=detail.profile||{},pr=detail.progress||{},a=detail.achievements||[];work.innerHTML=`<div class="staff-breadcrumb"><button data-users>Пользователи</button><span>›</span><span>${esc(p.display_name||p.email)}</span></div><header class="staff-profile-head"><img class="staff-avatar" src="${esc(avatar(p))}" alt=""><div><h3>${esc(p.display_name||'Без ника')}</h3><div class="staff-user-meta">${esc(p.email)} · ${esc(factionNames[p.faction]||'Без фракции')}</div></div><span class="staff-pill">Архив ${ranks[Math.min(+p.archive_level||0,5)]} · ${Number(pr.points||0).toLocaleString('ru-RU')} ОА</span></header><nav class="staff-tabs"><button data-tab="profile">Профиль</button><button data-tab="progress">Прогресс</button><button data-tab="rewards">Награды</button><button data-tab="moderation">Модерация</button><button data-tab="history">История</button></nav><div data-tab-body></div>`;work.querySelector('[data-users]').onclick=()=>{selected=null;loadUsers().catch(fail)};work.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===currentTab);b.onclick=()=>{currentTab=b.dataset.tab;renderUser()}});renderUserTab()}
function renderUserTab(){const body=work.querySelector('[data-tab-body]'),p=detail.profile||{},pr=detail.progress||{};if(currentTab==='profile'){body.innerHTML=`<div class="staff-grid"><article class="staff-card"><p class="eyebrow">Статус</p><h4>Учётная запись</h4><p>Архив ${ranks[Math.min(+p.archive_level||0,5)]}</p><p>${p.is_author?'Автор · TODM V':p.is_todm_team?'Команда · TODM IV':'Читатель'}</p><p>${p.is_supporter?'Поддержал TODM':'Без отметки поддержки'}</p></article><article class="staff-card"><p class="eyebrow">Доступ</p><h4>Состояние</h4><p>${p.full_access?'Полный доступ':'Доступ по уровню'}</p><p>${p.is_banned?'Аккаунт заблокирован':'Аккаунт активен'}</p><button class="staff-action" data-edit-access>Изменить права</button></article>${canGrantStaff&&p.faction?`<article class="staff-card staff-danger-zone"><p class="eyebrow">Фракция</p><h4>Сбросить принадлежность</h4><p>Удалит выбор, отметку первого вступления, связанные 20 ОА, лидерство и историю прочтения фракционного чата.</p><button class="staff-action danger" data-reset-faction>Убрать фракцию полностью</button></article>`:''}</div>`;body.querySelector('[data-edit-access]').onclick=editAccess;body.querySelector('[data-reset-faction]')?.addEventListener('click',resetFaction)}
else if(currentTab==='progress'){const r=detail.reading||{};body.innerHTML=`<div class="staff-grid"><article class="staff-card"><p class="eyebrow">Очки Архива</p><div class="staff-stat">${Number(pr.points||0).toLocaleString('ru-RU')} ОА</div><button class="staff-action primary" data-points>Скорректировать ОА</button></article><article class="staff-card"><p class="eyebrow">Испытание I</p><h4>${pr.archive_i_test_passed?'Пройдено':'Не пройдено'}</h4><p>Лучший результат: ${pr.best_archive_i_test_score||0}/12</p></article><article class="staff-card"><h4>Бесплатное чтение</h4><div class="staff-checks">${[['Пролог',r.prologue],['Глава 1',r.chapter_1],['Глава 2',r.chapter_2],['Глава 3',r.chapter_3]].map(([n,v])=>`<div class="staff-check ${v?'done':''}">${v?'✓':'—'} ${n}</div>`).join('')}</div></article><article class="staff-card"><h4>Активность</h4><p>${Math.floor((pr.active_seconds||0)/3600)} ч активного времени</p><p>${pr.completed_games||0} игр · ${pr.won_games||0} побед</p></article></div>`;body.querySelector('[data-points]').onclick=adjustPoints}
else if(currentTab==='rewards')renderRewards(body);
else if(currentTab==='moderation')renderModeration(body);
else renderLedger(body)}
function renderRewards(body){const items=detail.achievements||[];body.innerHTML=`<div class="reward-grid">${items.map(a=>`<article class="reward-card ${a.owned?'':'locked'}"><span class="staff-pill">${esc(a.rarity)}</span><h4>${esc(a.title)}</h4><p>${esc(a.description)}</p><p>${a.manual_points?`${a.manual_points>0?'+':''}${a.manual_points} ОА`:'Коллекционная награда'}</p><button class="staff-action ${a.owned?'danger':'primary'}" data-reward="${esc(a.code)}">${a.owned?'Отозвать':'Выдать'}</button></article>`).join('')}</div>`;body.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>rewardAction(items.find(a=>a.code===b.dataset.reward)))}
function rewardAction(a){const rev=Boolean(a.owned),delta=rev?-a.manual_points:a.manual_points;openModal({title:`${rev?'Отозвать':'Выдать'}: ${a.title}`,danger:rev,confirm:rev?'Отозвать':'Выдать',body:`<p>${esc(a.description)}</p><p>${delta?`Будет создана корректировка ${delta>0?'+':''}${delta} ОА.`:'ОА не изменятся.'}</p><label class="staff-field">Причина<textarea name="reason" minlength="5" maxlength="500" required placeholder="Обязательная причина действия"></textarea></label>`,onConfirm:async fd=>{const rpc=rev?'archive_staff_revoke_achievement':'archive_staff_grant_achievement',r=await TODMAuth.client.rpc(rpc,{p_user_id:selected,p_code:a.code,p_reason:fd.get('reason')});if(r.error)throw r.error;notify(rev?'Награда отозвана. Пользователь получит уведомление.':'Награда выдана. Пользователь получит уведомление.');await openUser(selected,'rewards')}})}
function adjustPoints(){openModal({title:'Скорректировать Очки Архива',body:'<p>Введите положительное или отрицательное изменение. Текущее значение не перезаписывается напрямую.</p><label class="staff-field">Изменение ОА<input name="amount" type="number" min="-1000000" max="1000000" required></label><label class="staff-field">Причина<textarea name="reason" minlength="5" maxlength="500" required></textarea></label>',onConfirm:async fd=>{const amount=Number(fd.get('amount'));if(!amount)throw Error('Изменение не может быть равно нулю.');const r=await TODMAuth.client.rpc('archive_staff_adjust_points',{p_user_id:selected,p_amount:amount,p_reason:fd.get('reason')});if(r.error)throw r.error;notify('ОА скорректированы. Запись добавлена в журнал.');await openUser(selected,'progress')}})}
function resetFaction(){const p=detail.profile||{};openModal({title:`Полностью убрать фракцию «${factionNames[p.faction]||p.faction}»?`,danger:true,confirm:'Убрать фракцию',body:'<p>Выбор и связанная прогрессия будут удалены так, будто пользователь никогда не выбирал фракцию. Сообщения пользователя в чатах сохранятся.</p><label class="staff-field">Причина<textarea name="reason" minlength="5" maxlength="500" required></textarea></label>',onConfirm:async fd=>{const r=await TODMAuth.client.rpc('admin_reset_user_faction',{p_user_id:selected,p_reason:fd.get('reason')});if(r.error)throw r.error;notify('Фракция и связанная история сброшены.');await openUser(selected,'profile')}})}
function renderLedger(body){const rows=detail.ledger||[];body.innerHTML=`<div class="staff-ledger">${rows.length?rows.map(x=>`<div class="staff-ledger-row"><strong>${x.amount>0?'+':''}${x.amount} ОА</strong><span>${esc(x.event_code.replaceAll('_',' '))}${x.reason?`<small><br>${esc(x.reason)}</small>`:''}</span><time>${new Date(x.created_at).toLocaleString('ru-RU')}</time></div>`).join(''):'<p class="staff-empty">История прогресса пуста.</p>'}</div>`}
function renderModeration(body){const p=detail.profile||{};body.innerHTML=`<div class="staff-grid"><article class="staff-card"><p class="eyebrow">Общение</p><h4>Ограничения чатов</h4><label><input type="checkbox" data-general ${p.mute_general_chat?'checked':''}> Запрет общего чата</label><br><label><input type="checkbox" data-faction ${p.mute_faction_chat?'checked':''}> Запрет чата фракции</label><p><button class="staff-action" data-save-chat>Сохранить ограничения</button></p></article><article class="staff-card"><p class="eyebrow">Портрет</p><h4>${p.avatar_hidden?'Портрет скрыт':'Портрет виден'}</h4><button class="staff-action ${p.avatar_hidden?'':'danger'}" data-avatar>${p.avatar_hidden?'Вернуть портрет':'Скрыть портрет'}</button></article><article class="staff-card"><p class="eyebrow">Предупреждение</p><h4>Официальное сообщение</h4><a class="staff-action" href="AdminWarnings.html?user=${selected}">Открыть предупреждения</a></article><article class="staff-card staff-danger-zone"><p class="eyebrow">Опасное действие</p><h4>${p.is_banned?'Снять блокировку':'Заблокировать аккаунт'}</h4><p>Изменение требует отдельного подтверждения.</p><button class="staff-action danger" data-ban>${p.is_banned?'Разблокировать':'Заблокировать'}</button></article></div>`;body.querySelector('[data-save-chat]').onclick=async()=>{const r=await TODMAuth.client.rpc('admin_set_chat_restrictions',{p_user_id:selected,p_mute_general:body.querySelector('[data-general]').checked,p_mute_faction:body.querySelector('[data-faction]').checked});if(r.error)return notify(msg(r.error));notify('Ограничения общения сохранены.');await openUser(selected,'moderation')};body.querySelector('[data-avatar]').onclick=()=>simpleConfirm(p.avatar_hidden?'Вернуть портрет пользователя?':'Скрыть портрет от всех пользователей?',!p.avatar_hidden,async()=>{const r=await TODMAuth.client.rpc('admin_set_avatar_hidden',{p_user_id:selected,p_hidden:!p.avatar_hidden});if(r.error)throw r.error;notify('Состояние портрета изменено.');await openUser(selected,'moderation')});body.querySelector('[data-ban]').onclick=()=>changeBan(!p.is_banned)}
function editAccess(){const p=detail.profile||{};if(!isFullAdmin)return notify('Уровни и полный доступ изменяет только администратор.');openModal({title:'Изменить права пользователя',body:`<div class="staff-form-grid"><label class="staff-field">Уровень<select name="level">${ranks.map((x,i)=>`<option value="${i}" ${i===+p.archive_level?'selected':''}>${x}</option>`).join('')}</select></label><label class="staff-field"><span>Полный доступ</span><input name="full" type="checkbox" ${p.full_access?'checked':''}></label></div><p>Статус Автора этой формой не изменяется.</p>`,onConfirm:async fd=>{const level=+fd.get('level');if(level===5&&!p.is_author)throw Error('TODM V нельзя назначить этой формой.');const r=await TODMAuth.client.rpc('admin_update_access',{p_user_id:selected,p_level:level,p_team:level>=4,p_full:fd.get('full')==='on'||level>=4,p_banned:p.is_banned,p_updated_at:p.updated_at||new Date().toISOString()});if(r.error)throw r.error;notify('Права пользователя обновлены.');await openUser(selected,'profile')}})}
function changeBan(next){const p=detail.profile||{};if(!isFullAdmin)return notify('Блокировку может менять только администратор.');openModal({title:next?'Заблокировать пользователя?':'Снять блокировку?',danger:next,confirm:next?'Заблокировать':'Разблокировать',body:'<label class="staff-field">Причина<textarea name="reason" minlength="5" maxlength="500" required></textarea></label>',onConfirm:async()=>{const r=await TODMAuth.client.rpc('admin_update_access',{p_user_id:selected,p_level:+p.archive_level,p_team:p.is_todm_team,p_full:p.full_access,p_banned:next,p_updated_at:p.updated_at||new Date().toISOString()});if(r.error)throw r.error;notify(next?'Пользователь заблокирован.':'Пользователь разблокирован.');await openUser(selected,'moderation')}})}
function simpleConfirm(title,danger,onConfirm){openModal({title,danger,confirm:'Подтвердить',body:'<p>Действие будет зафиксировано системой.</p>',onConfirm})}
async function renderAudit(){loading();const r=await TODMAuth.client.rpc('archive_staff_audit',{p_filter:auditFilter,p_offset:0});if(r.error)throw r.error;const rows=r.data||[],filters={ALL:'Все',ACHIEVEMENTS:'Награды',POINTS:'ОА',MODERATION:'Модерация',RANKS:'Ранги',SYSTEM:'Система'};work.innerHTML=`<div class="staff-title-row"><div><p class="eyebrow">Неизменяемая история</p><h3>Журнал Архива</h3></div></div><div class="audit-filters">${Object.entries(filters).map(([k,v])=>`<button data-filter="${k}" class="${k===auditFilter?'active':''}">${v}</button>`).join('')}</div><div class="staff-audit-list">${rows.length?rows.map(x=>`<article class="staff-audit-row"><strong>${esc(x.actor_name)}</strong><span>${esc(x.action.replaceAll('_',' '))}<br><small>${esc(x.target_name)}${x.reason?` · ${esc(x.reason)}`:''}</small></span><time>${new Date(x.created_at).toLocaleString('ru-RU')}</time></article>`).join(''):'<p class="staff-empty">Записей по выбранному фильтру нет.</p>'}</div>`;work.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{auditFilter=b.dataset.filter;renderAudit().catch(fail)})}
function renderInfo(type){const info={rewards:['Награды','Выберите пользователя в разделе «Пользователи», затем откройте вкладку «Награды».'],notifications:['Уведомления','Автоматические уведомления о наградах и ОА доставляются через очередь Архива. Для ручного предупреждения используйте отдельный редактор.'],moderation:['Модерация','Выберите пользователя, чтобы открыть ограничения чатов, управление портретом, предупреждения и блокировку.']}[type];work.innerHTML=`<div class="staff-title-row"><div><p class="eyebrow">Управление Архивом</p><h3>${info[0]}</h3></div></div><p class="staff-empty">${info[1]}</p>${type==='notifications'?'<p><a class="staff-action" href="AdminWarnings.html">Открыть редактор предупреждений</a></p>':''}`}
function renderSection(s){if(s==='users')loadUsers().catch(fail);else if(s==='audit')renderAudit().catch(fail);else renderInfo(s)}
function fail(e){work.innerHTML=`<p class="staff-empty">Не удалось загрузить раздел: ${esc(msg(e))}</p>`;notify(msg(e))}
const leadershipObserver=new MutationObserver(()=>{if(currentTab!=='profile'||!selected||!detail?.profile||work.querySelector('[data-leadership]'))return;const host=work.querySelector('[data-tab-body] .staff-grid');if(!host)return;const p=detail.profile,card=document.createElement('article');card.className='staff-card';card.dataset.leadership='';card.innerHTML=`<p class="eyebrow">Фракция</p><h4>Лидерство</h4><label class="staff-field">Статус<select>${`<option value="">Не является лидером</option>${Object.entries(factionNames).map(([id,name])=>`<option value="${id}" ${p.leader_faction===id?'selected':''}>Лидер: ${name}</option>`).join('')}`}</select></label><p><button class="staff-action" type="button">Сохранить лидерство</button></p>`;const select=card.querySelector('select'),button=card.querySelector('button');button.onclick=()=>{if(!isFullAdmin)return notify('Лидерство изменяет только администратор.');const old=p.leader_faction||'',next=select.value;openModal({title:next?'Назначить лидера фракции?':'Снять лидерство?',danger:!next,body:'<p>Изменение будет записано в журнал и пользователь получит системное уведомление.</p>',onConfirm:async()=>{const faction=next||old;if(!faction)throw Error('Пользователь не является лидером.');const r=await TODMAuth.client.rpc('admin_set_faction_leader',{p_faction:faction,p_user_id:next?selected:null});if(r.error)throw r.error;notify(next?'Лидер фракции назначен.':'Лидерство снято.');await openUser(selected,'profile')}})};host.append(card)});leadershipObserver.observe(work,{childList:true,subtree:true});
const staffOptionGuard=new MutationObserver(()=>{if(canGrantStaff)return;modal.querySelectorAll('select[name="level"] option').forEach(o=>{if(Number(o.value)>=4)o.remove()});const p=detail?.profile;if(p&&(p.user_id==='8cd4aa8b-a90a-4e67-9112-9dbc170c27bc'||p.is_todm_team||Number(p.archive_level)>=4))work.querySelector('[data-ban]')?.remove()});staffOptionGuard.observe(modal,{childList:true,subtree:true});staffOptionGuard.observe(work,{childList:true,subtree:true});
async function init(){try{account=await TODMAuth.getAccount();if(!account.session){location.replace('Auth.html?next=Admin.html');return}canGrantStaff=Boolean(account.access?.is_admin||account.access?.is_author);isFullAdmin=Boolean(canGrantStaff||account.access?.is_todm_team);if(account.access?.is_banned||!isFullAdmin){say('Доступ разрешён только TODM IV/V.');$('[data-open-panel]').disabled=true;return}say(canGrantStaff?'Полномочия TODM V подтверждены.':'Полномочия TODM IV подтверждены.')}catch(e){say(`Панель недоступна: ${msg(e)}`);$('[data-open-panel]').disabled=true}}
if(window.TODMAuth)init();else addEventListener('todm-auth-ready',init,{once:true});
})();
