(()=>{'use strict';const style=document.createElement('link');style.rel='stylesheet';style.href='admin-leadership.css';document.head.append(style);
const $=s=>document.querySelector(s),status=$('#status');let offset=0,query='',busy=false,leaders={},isFullAdmin=false;
const say=t=>status.textContent=t;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n};
const ranks=['0 — базовый','I','II','III','IV — сотрудник','V — владелец'];
function render(row){
 const card=el('article',null,'admin-user'),heading=el('h2',row.display_name||'Без ника');card.append(heading,el('p',row.email,'email'));
 if(row.is_todm_team)card.append(el('span','TODM','badge todm'));if(row.is_author)card.append(el('span','Автор','badge author'));
 const form=el('form',null,'admin-fields'),level=el('select');level.setAttribute('aria-label','Ранг');ranks.forEach((name,i)=>{if(i===5&&row.archive_level!==5)return;const o=el('option',name);o.value=i;level.append(o)});level.value=row.archive_level;const lab=el('label','Уровень');lab.append(level);form.append(lab);
 const check=(title,value)=>{const l=el('label',title),input=el('input');input.type='checkbox';input.checked=value;l.prepend(input);form.append(l);return input};
 const team=check('Плашка TODM',row.is_todm_team),full=check('Полный доступ',row.full_access),ban=check('Заблокирован',row.is_banned),muteGeneral=check('Запрет общего чата',row.mute_general_chat),muteFaction=check('Запрет чата фракции',row.mute_faction_chat),save=el('button','Сохранить');save.type='submit';form.append(save);
 const sync=()=>{team.checked=Number(level.value)>=4;if(team.checked)full.checked=true;full.disabled=team.checked};
 level.addEventListener('change',sync);team.addEventListener('change',()=>{level.value=team.checked?'4':'0';full.checked=team.checked;sync()});sync();
 if(!isFullAdmin){[level,team,full,ban].forEach(n=>n.disabled=true)}
 if(row.is_admin||row.archive_level===5){form.querySelectorAll('input,select,button').forEach(n=>n.disabled=true);card.append(el('p','Защищённый аккаунт администратора / владельца'));}
 form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(!confirm(`Сохранить права пользователя ${row.email}? Уровень: ${ranks[Number(level.value)]}. TODM: ${team.checked?'да':'нет'}. Полный доступ: ${full.checked?'да':'нет'}. Бан: ${ban.checked?'да':'нет'}. Запрет общего чата: ${muteGeneral.checked?'да':'нет'}. Запрет чата фракции: ${muteFaction.checked?'да':'нет'}.`))return;
 busy=true;save.disabled=true;say('Сохраняем…');try{if(isFullAdmin){const access=await TODMAuth.client.rpc('admin_update_access',{p_user_id:row.user_id,p_level:Number(level.value),p_team:team.checked,p_full:full.checked,p_banned:ban.checked,p_updated_at:row.updated_at});if(access.error)throw access.error}const restrictions=await TODMAuth.client.rpc('admin_set_chat_restrictions',{p_user_id:row.user_id,p_mute_general:muteGeneral.checked,p_mute_faction:muteFaction.checked});if(restrictions.error)throw restrictions.error;await load();say('Изменения сохранены.');}catch(e){say(`Не удалось сохранить: ${TODMAuth.message(e)}`)}finally{busy=false;save.disabled=false}});
 card.append(form);if(isFullAdmin)addLeaderControl(card,row);return card;
}
const factionNames={dokains:'Докаины',frauster:'Фраустер',maizervin:'Майзервин',paladins:'Паладины',doronto:'Культ Доронто'};
function addLeaderControl(card,row){const wrap=el('div',null,'leader-control'),label=el('label','Лидерство'),select=el('select'),save=el('button','Сохранить лидерство');select.setAttribute('aria-label','Лидер фракции');select.append(new Option('Не является лидером',''));Object.entries(factionNames).forEach(([id,name])=>select.append(new Option(`Лидер: ${name}`,id)));select.value=Object.entries(leaders).find(([,id])=>id===row.user_id)?.[0]||'';save.type='button';save.onclick=async()=>{if(busy)return;busy=true;save.disabled=true;try{const current=Object.entries(leaders).find(([,id])=>id===row.user_id)?.[0]||null,target=select.value||current;if(!target)throw Error('Пользователь не является лидером.');const{error}=await TODMAuth.client.rpc('admin_set_faction_leader',{p_faction:target,p_user_id:select.value?row.user_id:null});if(error)throw error;await load();say(select.value?'Лидер фракции назначен.':'Лидерство снято.')}catch(e){say(`Не удалось изменить лидерство: ${TODMAuth.message(e)}`)}finally{busy=false;save.disabled=false}};label.append(select);wrap.append(label,save);card.append(wrap)}
async function load(){const users=await TODMAuth.client.rpc('admin_list_users',{p_search:query,p_offset:offset});if(users.error){$('#users').replaceChildren();throw users.error}const data=users.data||[];if(isFullAdmin){const leaderResult=await TODMAuth.client.from('faction_leaders').select('faction,user_id');if(leaderResult.error)throw leaderResult.error;leaders=Object.fromEntries((leaderResult.data||[]).map(x=>[x.faction,x.user_id]))}const{data:restrictions,error:restrictionError}=await TODMAuth.client.rpc('admin_chat_restrictions',{p_user_ids:data.map(row=>row.user_id)});if(restrictionError)throw restrictionError;const byUser=Object.fromEntries((restrictions||[]).map(row=>[row.user_id,row]));data.forEach(row=>Object.assign(row,byUser[row.user_id]||{}));$('#users').replaceChildren(...data.map(render));$('#prev').disabled=offset===0;$('#next').disabled=data.length<50;$('#page').textContent=`Страница ${offset/50+1}`;say(data.length?'Список загружен.':'Пользователи не найдены.');}
async function navigate(delta){if(busy)return;busy=true;offset=Math.max(0,offset+delta);try{await load()}catch(e){say(TODMAuth.message(e))}finally{busy=false}}
$('#search').addEventListener('submit',e=>{e.preventDefault();if(busy)return;query=new FormData(e.currentTarget).get('query').trim();offset=0;navigate(0)});$('#prev').onclick=()=>navigate(-50);$('#next').onclick=()=>navigate(50);
async function init(){try{const a=await TODMAuth.getAccount();if(!a.session){location.replace('Auth.html?next=Admin.html');return}isFullAdmin=Boolean(a.access?.is_admin);const canRestrict=isFullAdmin||(a.access?.is_todm_team&&a.access?.archive_level>=4);if(!canRestrict||a.access.is_banned){say('Доступ только для администратора или сотрудника IV ранга.');return}if(!isFullAdmin)document.querySelector('#panel>p').textContent='Вы можете запрещать пользователям отправку сообщений в общем и фракционном чатах. Остальные права доступны только администратору.';await load();$('#panel').hidden=false}catch(e){say(`Панель недоступна: ${TODMAuth.message(e)}`)}}
if(window.TODMAuth)init();else addEventListener('todm-auth-ready',init,{once:true});
})();
