(()=>{'use strict';
const $=s=>document.querySelector(s),status=$('#status'),box=$('#messages'),input=$('#message');let account,before=null,oldest=null,loading=false,sending=false,signature='',timer;
const factions={dokains:'Докаины',frauster:'Фраустер',maizervin:'Майзервин',paladins:'Паладины',doronto:'Культ Доронто'},ranks=['','I','II','III','IV TODM','V Автор'];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function message(row){const article=el('article',undefined,'chat-message');const fallback=el('span',(row.display_name||'Ч').slice(0,1).toUpperCase(),'chat-avatar');article.append(fallback);
if(row.avatar_url){try{const u=new URL(row.avatar_url);if(u.protocol==='https:'){const img=el('img');img.className='chat-avatar';img.alt='Аватар';img.loading='lazy';img.referrerPolicy='no-referrer';img.src=u.href;img.onerror=()=>img.replaceWith(fallback);fallback.replaceWith(img)}}catch{}}
const content=el('div',undefined,'message-content'),head=el('div',undefined,'message-head');head.append(el('strong',row.display_name||'Читатель'));
if(ranks[row.archive_level])head.append(el('span',ranks[row.archive_level],`badge ${row.archive_level===5?'author':row.is_todm_team?'todm':''}`));if(factions[row.selected_faction])head.append(el('span',factions[row.selected_faction],'faction'));
const time=el('time',new Date(row.created_at).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}));time.dateTime=row.created_at;head.append(time);content.append(head,el('p',row.deleted?'Сообщение удалено модератором':row.body,row.deleted?'message-body message-deleted':'message-body'));
if(!row.deleted&&(account.access.is_admin||account.access.is_todm_team)){const button=el('button','Удалить','delete-message');button.type='button';button.onclick=async()=>{if(!confirm('Удалить это сообщение из чата?'))return;button.disabled=true;try{const{error}=await TODMAuth.client.rpc('chat_delete',{p_id:row.id});if(error)throw error;await load()}catch(e){status.textContent=TODMAuth.message(e)}finally{button.disabled=false}};content.append(button)}article.append(content);return article;}
async function load(){if(loading)return;loading=true;try{const{data,error}=await TODMAuth.client.rpc('chat_list',{p_before:before});if(error)throw error;const sig=JSON.stringify(data);if(sig!==signature){const bottom=box.scrollHeight-box.scrollTop-box.clientHeight<90,position=box.scrollTop;box.replaceChildren(...[...data].reverse().map(message));if(!data.length)box.append(el('p','Сообщений пока нет. Начните разговор.'));box.scrollTop=bottom||!signature?box.scrollHeight:position;signature=sig}oldest=data.at(-1)?.id||null;$('#older').disabled=data.length<60;$('#latest').disabled=before===null;status.textContent=before?'Просмотр истории сообщений.':'Чат подключён · обновление каждые 5 секунд';}catch(e){status.textContent=`Не удалось обновить чат: ${TODMAuth.message(e)}`;if(e.code==='42501'){$('#chat').hidden=true;clearInterval(timer)}}finally{loading=false}}
$('#older').onclick=()=>{if(loading||!oldest)return;before=oldest;signature='';load()};$('#latest').onclick=()=>{if(loading)return;before=null;signature='';load()};
['😀','😊','😂','❤️','👍','🔥','🎉','🤔','😢','👀','⚔️','🐉'].forEach(emoji=>{const b=el('button',emoji);b.type='button';b.setAttribute('aria-label',`Добавить ${emoji}`);b.onclick=()=>{if(input.value.length+emoji.length>2000)return;const start=input.selectionStart,end=input.selectionEnd;input.setRangeText(emoji,start,end,'end');input.focus()};$('#emojis').append(b)});
$('#compose').onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(sending||!body)return;sending=true;$('#send').disabled=true;try{const{error}=await TODMAuth.client.rpc('chat_send',{p_body:body});if(error)throw error;input.value='';before=null;signature='';await load()}catch(e){status.textContent=TODMAuth.message(e)}finally{sending=false;$('#send').disabled=false}};
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#compose').requestSubmit()}});
async function init(){try{account=await TODMAuth.getAccount();if(!account.session){location.replace('Auth.html?next=Chat.html');return}if(!account.access||account.access.is_banned){status.textContent='Чат недоступен: аккаунт заблокирован.';return}$('#chat').hidden=false;await load();timer=setInterval(()=>{if(!document.hidden)load()},5000)}catch(e){status.textContent=`Не удалось войти в чат: ${TODMAuth.message(e)}`}}
addEventListener('pagehide',()=>clearInterval(timer));if(window.TODMAuth)init();else addEventListener('todm-auth-ready',init,{once:true});
})();
