(()=>{'use strict';
  const status=document.querySelector('[data-archive-status]'),documentRoot=document.querySelector('[data-archive-document]');
  let initializing=false,finished=false;
  const withTimeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))]);
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const deny=(title,text,login=false)=>{status.className='archive-status denied';status.innerHTML=`<span class="status-seal">×</span><p class="eyebrow">Доступ отклонён</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(text)}</p><div class="gate-actions">${login?`<a class="button" href="Auth.html?next=${encodeURIComponent('Dokains_Archive.html')}">Войти</a>`:''}<a href="Dokains.html">Вернуться к докаинам</a></div>`};
  const section=(eyebrow,title,paragraphs)=>`<section class="record-section" data-reveal><header><p class="eyebrow">${escapeHtml(eyebrow)}</p><h2>${escapeHtml(title)}</h2></header><div class="record-copy">${paragraphs.map(p=>`<p>${escapeHtml(p)}</p>`).join('')}</div></section>`;
  const visual=(src,alt,caption,variant='wide')=>`<figure class="archive-visual archive-visual--${variant}" data-reveal><img src="${src}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
  const render=async body=>{let imageUrl='';if(body.image_path){const{data,error}=await TODMAuth.client.storage.from('archive-media').createSignedUrl(body.image_path,900);if(!error)imageUrl=data.signedUrl;else{console.error('Private archive image unavailable:',error);if(['127.0.0.1','localhost'].includes(location.hostname))imageUrl='images/dokains-archive-infographic.png'}}
    const sections=body.sections||[];
    documentRoot.innerHTML=`<section class="record-hero"><img class="record-hero-media" src="images/dokains-archive-hero.png" alt="Докаин среди руин под затмением"><nav class="breadcrumbs"><a href="Tom_I.html">Том I</a><span>→</span><a href="Dokains.html">Докаины</a><span>→</span><span>Архив DKN–01</span></nav><p class="eyebrow">Допуск подтверждён · уровень I</p><h1>${escapeHtml(body.title)}</h1><p>${escapeHtml(body.lead)}</p><span class="declassified-stamp">Рассекречено частично</span></section>${sections[0]?section(sections[0].eyebrow,sections[0].title,sections[0].paragraphs||[]):''}${visual('images/dokains-archive-clearance.png','Архивная карточка первого уровня допуска','Архивный допуск I · базовые материалы','framed')}${sections[1]?section(sections[1].eyebrow,sections[1].title,sections[1].paragraphs||[]):''}${visual('images/dokains-archive-aftermath.png','Докаины среди руин исследовательского комплекса','Проект «Чернхорн» · сектор B–17')}${sections.slice(2,4).map(s=>section(s.eyebrow,s.title,s.paragraphs||[])).join('')}${visual('images/dokains-archive-core.png','Архивная схема внутренней структуры и ядра докаина','Внутренняя структура · энергетическое ядро','square')}${sections.slice(4).map(s=>section(s.eyebrow,s.title,s.paragraphs||[])).join('')}<section class="core-metrics" data-reveal><div><p class="eyebrow">Параметры ядра</p><h2>Плотность и стабильность</h2></div><article><span>Плотность</span><div class="metric"><i style="--value:62%"></i></div><p>Определяет количество энергии, находящейся в докаине.</p></article><article><span>Стабильность</span><div class="metric"><i style="--value:74%"></i></div><p>Определяет, насколько хорошо ядро выдерживает изменения и воздействие.</p></article><small>Шкалы являются архивной схемой обычного докаина и не раскрывают сравнительную классификацию.</small></section>${imageUrl?`<figure class="archive-plate" data-reveal><a href="${escapeHtml(imageUrl)}" target="_blank" rel="noopener" aria-label="Открыть инфографику в полном размере"><img src="${escapeHtml(imageUrl)}" alt="Архивная инфографика об устройстве докаинов" loading="lazy"></a><figcaption>Архивная пластина DKN–01 · нажмите, чтобы открыть крупнее</figcaption></figure>`:'<section class="image-unavailable"><p>Архивная иллюстрация временно недоступна.</p></section>'}<section class="classified-block" data-reveal><p class="eyebrow">Архив III</p><h2>Классификация докаинов</h2><div>${Array.from({length:4},()=>'<span>[ ЗАСЕКРЕЧЕНО ]</span>').join('')}</div><strong>РАССЕКРЕЧИВАЕТСЯ НА УРОВНЕ АРХИВА III</strong><p>Сведения о классах, их характеристиках и сравнительных показателях ядра изъяты из этой версии документа.</p></section><nav class="record-return"><a href="Dokains.html">← Вернуться к основной записи о докаинах</a></nav>`;
    documentRoot.hidden=false;status.remove();documentRoot.querySelectorAll('[data-reveal]').forEach(el=>requestAnimationFrame(()=>el.classList.add('visible')))};
  const init=async()=>{if(initializing||finished)return;initializing=true;try{const account=await withTimeout(TODMAuth.getAccount(),12000,'Превышено время проверки профиля');if(!account.session){finished=true;return deny('Требуется авторизация','Эта запись доступна читателям с уровнем Архива I и выше.',true)}if(!account.access||account.access.is_banned||(!account.access.full_access&&Number(account.access.archive_level)<1)){finished=true;return deny('Недостаточный уровень допуска','Архив не обнаружил уровень I, необходимый для чтения этой записи.')}const{data,error}=await withTimeout(TODMAuth.client.from('archive_content').select('body').eq('slug','dokains-anatomy').maybeSingle(),12000,'Превышено время загрузки записи');if(error)throw error;if(!data){finished=true;return deny('Запись не опубликована','Материал ещё не активирован в Архиве.')}await withTimeout(render(data.body||{}),12000,'Превышено время загрузки иллюстрации');finished=true}catch(error){console.error('Dokains archive access failed:',error);deny('Архив временно недоступен','Не удалось подтвердить доступ. Проверьте соединение и повторите попытку.');const actions=status.querySelector('.gate-actions');if(actions)actions.insertAdjacentHTML('afterbegin','<button class="button" type="button" data-archive-retry>Повторить проверку</button>');status.querySelector('[data-archive-retry]')?.addEventListener('click',()=>{initializing=false;status.className='archive-status';status.innerHTML='<span class="status-seal">I</span><p>Архив повторно проверяет уровень допуска…</p>';init()},{once:true})}finally{initializing=false}};
  const boot=()=>window.TODMAuth?init():null;
  if(!boot())addEventListener('todm-auth-ready',boot,{once:true});
  setTimeout(()=>{if(!finished&&!initializing){if(window.TODMAuth)init();else deny('Система авторизации не загрузилась','Обновите страницу без кэша или проверьте, не блокирует ли браузер загрузку Supabase.')}},5000);
})();
