(()=>{'use strict';
  const status=document.querySelector('[data-archive-status]'),documentRoot=document.querySelector('[data-archive-document]');
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const deny=(title,text,login=false)=>{status.className='archive-status denied';status.innerHTML=`<span class="status-seal">×</span><p class="eyebrow">Доступ отклонён</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(text)}</p><div class="gate-actions">${login?`<a class="button" href="Auth.html?next=${encodeURIComponent('Dokains_Archive.html')}">Войти</a>`:''}<a href="Dokains.html">Вернуться к докаинам</a></div>`};
  const section=(eyebrow,title,paragraphs)=>`<section class="record-section" data-reveal><header><p class="eyebrow">${escapeHtml(eyebrow)}</p><h2>${escapeHtml(title)}</h2></header><div class="record-copy">${paragraphs.map(p=>`<p>${escapeHtml(p)}</p>`).join('')}</div></section>`;
  const render=async body=>{let imageUrl='';if(body.image_path){const{data,error}=await TODMAuth.client.storage.from('archive-media').createSignedUrl(body.image_path,900);if(!error)imageUrl=data.signedUrl;else{console.error('Private archive image unavailable:',error);if(['127.0.0.1','localhost'].includes(location.hostname))imageUrl='images/dokains-archive-infographic.png'}}
    documentRoot.innerHTML=`<section class="record-hero"><nav class="breadcrumbs"><a href="Tom_I.html">Том I</a><span>→</span><a href="Dokains.html">Докаины</a><span>→</span><span>Архив DKN–01</span></nav><p class="eyebrow">Допуск подтверждён · уровень I</p><h1>${escapeHtml(body.title)}</h1><p>${escapeHtml(body.lead)}</p><span class="declassified-stamp">Рассекречено частично</span></section>${(body.sections||[]).map(s=>section(s.eyebrow,s.title,s.paragraphs||[])).join('')}<section class="core-metrics" data-reveal><div><p class="eyebrow">Параметры ядра</p><h2>Плотность и стабильность</h2></div><article><span>Плотность</span><div class="metric"><i style="--value:62%"></i></div><p>Определяет количество энергии, находящейся в докаине.</p></article><article><span>Стабильность</span><div class="metric"><i style="--value:74%"></i></div><p>Определяет, насколько хорошо ядро выдерживает изменения и воздействие.</p></article><small>Шкалы являются архивной схемой обычного докаина и не раскрывают сравнительную классификацию.</small></section>${imageUrl?`<figure class="archive-plate" data-reveal><a href="${escapeHtml(imageUrl)}" target="_blank" rel="noopener" aria-label="Открыть инфографику в полном размере"><img src="${escapeHtml(imageUrl)}" alt="Архивная инфографика об устройстве докаинов" loading="lazy"></a><figcaption>Архивная пластина DKN–01 · нажмите, чтобы открыть крупнее</figcaption></figure>`:'<section class="image-unavailable"><p>Архивная иллюстрация временно недоступна.</p></section>'}<section class="classified-block" data-reveal><p class="eyebrow">Архив III</p><h2>Классификация докаинов</h2><div>${Array.from({length:4},()=>'<span>[ ЗАСЕКРЕЧЕНО ]</span>').join('')}</div><strong>РАССЕКРЕЧИВАЕТСЯ НА УРОВНЕ АРХИВА III</strong><p>Сведения о классах, их характеристиках и сравнительных показателях ядра изъяты из этой версии документа.</p></section><nav class="record-return"><a href="Dokains.html">← Вернуться к основной записи о докаинах</a></nav>`;
    status.hidden=true;documentRoot.hidden=false;documentRoot.querySelectorAll('[data-reveal]').forEach(el=>requestAnimationFrame(()=>el.classList.add('visible')))};
  const init=async()=>{try{const account=await TODMAuth.getAccount();if(!account.session)return deny('Требуется авторизация','Эта запись доступна читателям с уровнем Архива I и выше.',true);if(!account.access||account.access.is_banned||(!account.access.full_access&&Number(account.access.archive_level)<1))return deny('Недостаточный уровень допуска','Архив не обнаружил уровень I, необходимый для чтения этой записи.');const{data,error}=await TODMAuth.client.from('archive_content').select('body').eq('slug','dokains-anatomy').maybeSingle();if(error)throw error;if(!data)return deny('Запись не опубликована','Материал ещё не активирован в Архиве.');await render(data.body||{})}catch(error){console.error('Dokains archive access failed:',error);deny('Архив временно недоступен','Не удалось подтвердить доступ. Повторите попытку позднее.')}};
  if(window.TODMAuth)init();else addEventListener('todm-auth-ready',init,{once:true});
})();
