(()=>{'use strict';
  const volume=Number(document.body.dataset.volume),slug=document.body.dataset.contentSlug;
  const allowed=new Set('header nav main section article aside footer div span p h1 h2 h3 h4 h5 h6 a button img strong b em i small br hr ul ol li blockquote dl dt dd figure figcaption details summary table thead tbody tr th td'.split(' '));
  const asset=value=>{if(!value||!value.startsWith('images/')||value.includes('..')||/[\\\u0000-\u001f]/.test(value))return null;try{const u=new URL(value,location.href);return u.origin===location.origin?u.href:null}catch{return null}};
  const href=value=>{if(!value||/[\\\u0000-\u001f]/.test(value))return null;if(value.startsWith('#'))return value;if(!/^[A-Za-z0-9_-]+\.html(?:[?#].*)?$/.test(value))return null;return new URL(value,location.href).href};
  // Copy only inert, explicitly permitted nodes and attributes from editorial HTML.
  // Do not install scripts, handlers, embeds, forms, or arbitrary CSS from the database.
  function clean(node){if(node.nodeType===3)return document.createTextNode(node.textContent);if(node.nodeType!==1||!allowed.has(node.localName))return document.createDocumentFragment();const out=document.createElement(node.localName);for(const {name,value}of node.attributes){if(['class','id','title','alt','role','aria-label','aria-current','aria-expanded','aria-controls','data-header','data-menu-toggle','data-nav','data-year'].includes(name))out.setAttribute(name,value);else if(name==='href'&&node.localName==='a'){const safe=href(value);if(safe)out.setAttribute('href',safe)}else if(name==='src'&&node.localName==='img'){const safe=asset(value);if(safe)out.setAttribute('src',safe)}else if(name==='style'){const m=value.match(/^\s*(--image|--hero|--card-image)\s*:\s*url\(['"]?(images\/[^'"()]+)['"]?\)\s*;?\s*$/);if(m){const safe=asset(m[2]);if(safe)out.style.setProperty(m[1],`url("${safe.replace(/"/g,'%22')}")`)}}}if(node.localName==='button')out.type='button';for(const child of node.childNodes)out.append(clean(child));return out}
  function gate(message,login=false){const main=document.createElement('main');main.className='gate';const section=document.createElement('section');section.className='gate-card';const h=document.createElement('h1');h.textContent='Закрытый материал';const p=document.createElement('p');p.textContent=message;const link=document.createElement('a');const returnPage=location.pathname.split('/').pop()||'Tom_II.html';link.href=login?'Auth.html?next='+encodeURIComponent(returnPage):'Tom_II.html';link.textContent=login?'Войти':'К Тому II';section.append(h,p,link);main.append(section);document.body.replaceChildren(main)}
  async function boot(){try{if(!Number.isInteger(volume)||volume<1||!slug)return gate('Материал временно недоступен. Попробуйте позднее.');const a=await TODMAuth.getAccount();if(!a.session)return gate('Для доступа требуется вход и III уровень Архива.',true);if(!a.access||a.access.is_banned||!(a.access.full_access||Number(a.access.archive_level)>=3))return gate('Для доступа требуется III уровень Архива.');const {data,error}=await TODMAuth.client.from('tome_content').select('body').eq('volume',volume).eq('slug',slug).eq('is_published',true).maybeSingle();if(error||!data?.body?.html)return gate('Материал временно недоступен. Попробуйте позднее.');const parsed=new DOMParser().parseFromString(data.body.html,'text/html'),fragment=document.createDocumentFragment();for(const child of parsed.body.childNodes)fragment.append(clean(child));document.body.replaceChildren(fragment);document.querySelectorAll('[data-year]').forEach(n=>n.textContent=new Date().getFullYear());const h=document.querySelector('[data-header]'),b=document.querySelector('[data-menu-toggle]');if(h&&b)b.addEventListener('click',()=>{const open=h.classList.toggle('open');b.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)})}catch{gate('Не удалось проверить доступ. Попробуйте позднее.')}}
  if(window.TODMAuth)boot();else addEventListener('todm-auth-ready',boot,{once:true});
})();
