(()=>{'use strict';
const groups=[
{title:'Обзор',items:[
['Турунг-гарх','Планета пустынь, каменистых равнин, каньонов и древних городов','Tome_II_Turung_Garh.html','images/t2-hero.jpg']]},
{title:'Персонажи',intro:'Досье центральных персонажей без поздних сюжетных спойлеров.',items:[
['Персонажи','Саргарим и Марни — воспитанники Питомника, чьи пути определили события Тома II','Tome_II_Characters.html','images/t2-sargarim.jpg']]},
{title:'Фракции',intro:'Три самостоятельных центра силы Турунг-гарха.',items:[
['Фракции','Геронты, Демархи и Реликты — государство, демоническая сила и религия','Tome_II_Factions.html','images/t2-forces-hero.png']]},
{title:'Мир',items:[
['Питомник','Жестокая система для детей, оставшихся без семьи и признанного таланта','Tome_II_Nursery.html','images/t2-wasteland.jpg'],
['Ресурсы','Основа власти Геронтов и причина лишений населения','Tome_II_Resources.html','images/t2-resources.jpg'],
['Обелиски','Важные структуры, назначение которых пока не раскрыто','Tome_II_Obelisks.html','images/t2-obelisks.jpg']]},
{title:'Демоны, магия, артефакты и лор',items:[
['Демоны и контракты','Сила, цена договора и единая система Демархов','Tome_II_Demons.html','images/t2-demons.jpg'],
['Адское пламя','Высшая форма магии огня','Tome_II_Hellfire.html','images/t2-hellfire.jpg'],
['Мартли','Фундаментальная божественная сила, связанная с белой силой','Tome_II_Martli.html','images/t2-martli.jpg'],
['Колодец','Место концентрации силы мира демонов','Tome_II_Well.html','images/t2-demons.jpg']]}
];
const shell=()=>`<header class="site-header" data-header><div class="header-inner"><a class="brand" href="index.html"><span class="brand-mark">TODM</span><span>Сказки Мертвеца</span></a><button class="menu-toggle" data-menu type="button" aria-expanded="false">Меню</button><nav class="site-nav"><a href="index.html">Главная</a><a href="#characters">Персонажи</a><a href="#factions">Фракции</a><a href="Reed.html">Читать</a><a href="Account.html">Личный кабинет</a></nav></div></header>`;
const gate=kind=>{document.body.innerHTML=`<main class="gate"><section class="gate-card"><div class="gate-mark">III</div><p class="eyebrow">Ограниченный доступ</p><h1>Том II закрыт</h1><p>${kind==='guest'?'Для доступа требуется авторизация и III уровень Архива.':'Для доступа требуется III уровень Архива.'}</p><div class="gate-actions">${kind==='guest'?'<a class="button primary" href="Auth.html?next=Tom_II.html">Войти</a>':''}<a class="button" href="Reed.html">Вернуться к томам</a></div></section></main>`};
const render=()=>{document.body.innerHTML=shell()+`<main><section class="t2-hero" style="--hero:url('images/t2-hero.jpg')"><div class="hero-copy"><p class="eyebrow">Сказки Мертвеца · Том II</p><h1>Кризис Турунг-гарха</h1><p>История суровой планеты, где власть распределяет человеческие судьбы, вера противостоит порядку, а демоническая сила требует плату жизнью.</p><div class="gate-actions"><a class="button primary" href="#overview">Исследовать том</a><a class="button" href="Reed.html">Все тома</a></div></div></section><section class="content tome-directory">${groups.map((g,i)=>`<section class="directory-group" id="${i===0?'overview':i===1?'characters':i===2?'factions':'group-'+i}"><header class="section-head"><p class="eyebrow">Раздел ${String(i+1).padStart(2,'0')}</p><h2>${g.title}</h2>${g.intro?`<p>${g.intro}</p>`:''}</header><div class="chapter-grid">${g.items.map((s,j)=>`<article class="chapter" style="--image:url('${s[3]}')"><a href="${s[2]}"><span class="chapter-index">${String(j+1).padStart(2,'0')}</span><div><p class="chapter-status">Раздел открыт</p><h3>${s[0]}</h3><p>${s[1]}</p></div></a></article>`).join('')}</div></section>`).join('')}<aside class="tome-note"><h2>Преимущественно пустынный мир</h2><p>Турунг-гарх — планета, а не отдельное государство или крепость. Пустыни определяют её основной образ, но существуют и другие природные зоны.</p></aside></section></main><footer class="site-footer"><div class="footer-row"><span>© <span data-year></span> Сказки Мертвеца</span><span>Том II · Кризис Турунг-гарха</span><a href="Details.html">Реквизиты</a></div></footer>`;const h=document.querySelector('[data-header]'),b=document.querySelector('[data-menu]');b.onclick=()=>{const open=h.classList.toggle('open');b.setAttribute('aria-expanded',String(open))};document.querySelector('[data-year]').textContent=new Date().getFullYear()};
const boot=async()=>{try{if(!window.TODMAuth)await new Promise((ok,no)=>{addEventListener('todm-auth-ready',ok,{once:true});setTimeout(()=>no(Error('timeout')),10000)});const a=await TODMAuth.getAccount();if(!a.session)return gate('guest');if(!a.access||a.access.is_banned||!(a.access.full_access||Number(a.access.archive_level)>=3))return gate('level');render()}catch(e){console.error(e);document.body.innerHTML='<main class="gate"><section class="gate-card"><h1>Архив не ответил</h1><p>Обновите страницу и попробуйте снова.</p><button class="button primary" onclick="location.reload()">Повторить</button></section></main>'}};boot()})();
