(()=>{'use strict';
const sections=[
['01','Кто такой Саргарим','Главный герой Тома II и сильный маг','Tome_II_Sargarim.html','images/t2-sargarim.jpg',1],
['02','Кто такой Марни','Материал готовится к публикации','Tome_II_Marni.html','images/t2-marni.jpg',0],
['03','Что такое Турунг-гарх','Планета, на которой разворачиваются события','Tome_II_Turung_Garh.html','images/t2-hero.jpg',1],
['04','Геронты, Демархи, Реликты','Три независимых центра силы Турунг-гарха','Tome_II_Rulers.html','images/t2-forces-hero.png',1],
['05','Питомник','Материал готовится к публикации','Tome_II_Nursery.html','images/t2-wasteland.jpg',0],
['06','Демоны','Контракты и источник заимствованной силы','Tome_II_Demons.html','images/t2-demons.jpg',1],
['07','Адское пламя','Высшая форма магии огня','Tome_II_Hellfire.html','images/t2-hellfire.jpg',1],
['08','Ресурсы','Материал готовится к публикации','Tome_II_Resources.html','images/t2-resources.jpg',0],
['09','Мартли','Фундаментальная белая сила Вселенной','Tome_II_Martli.html','images/t2-martli.jpg',1],
['10','Обелиски','Материал готовится к публикации','Tome_II_Obelisks.html','images/t2-obelisks.jpg',0],
['11','Колодец','Средоточие силы мира демонов','Tome_II_Well.html','images/t2-demons.jpg',1]];
const shell=()=>`<header class="site-header" data-header><div class="header-inner"><a class="brand" href="index.html"><span class="brand-mark">TODM</span><span>Сказки Мертвеца</span></a><button class="menu-toggle" data-menu type="button" aria-expanded="false">Меню</button><nav class="site-nav" data-nav><a href="index.html">Главная</a><a href="index.html#volumes">Томы</a><a href="Reed.html">Читать</a><a href="Project.html">О проекте</a><a href="Support.html">Поддержать проект</a><a href="Chat.html">Чат</a></nav></div></header>`;
const footer=()=>`<footer class="site-footer"><div class="footer-row"><span>© <span data-year></span> Сказки Мертвеца</span><span>Том II · Кризис Турунг-гарха</span><a href="Details.html">Реквизиты</a></div></footer>`;
const gate=(kind)=>{document.body.innerHTML=`<main class="gate"><section class="gate-card"><div class="gate-mark">III</div><p class="eyebrow">Ограниченный доступ</p><h1>Том II закрыт</h1><p>${kind==='guest'?'Для доступа к Тому II требуется авторизация и III уровень Архива.':'Для доступа к Тому II требуется III уровень Архива.'}</p><div class="gate-actions">${kind==='guest'?'<a class="button primary" href="Auth.html?next=Tom_II.html">Войти</a>':''}<a class="button" href="Reed.html">Вернуться к томам</a></div></section></main>`};
const fail=()=>{document.body.innerHTML=`<main class="gate"><section class="gate-card"><p class="eyebrow">Ошибка проверки</p><h1>Архив не ответил</h1><p>Не удалось проверить уровень доступа. Обновите страницу или попробуйте войти заново.</p><div class="gate-actions"><button class="button primary" onclick="location.reload()">Повторить</button><a class="button" href="Account.html">Личный кабинет</a></div></section></main>`};
const nav=()=>{const h=document.querySelector('[data-header]'),b=document.querySelector('[data-menu]');b?.addEventListener('click',()=>{const o=h.classList.toggle('open');b.setAttribute('aria-expanded',String(o));document.body.classList.toggle('menu-open',o)});document.querySelector('[data-year]').textContent=new Date().getFullYear()};
const render=()=>{document.body.innerHTML=shell()+`<main><section class="t2-hero" style="--hero:url('images/t2-hero.jpg')"><div class="hero-copy"><p class="eyebrow">Сказки Мертвеца · Том II</p><h1>Кризис Турунг-гарха</h1><p>История сильного мага на суровой планете, где пустыня хранит древние структуры, а цена заимствованной силы определяется условиями контракта.</p><div class="gate-actions"><a class="button primary" href="#materials">Исследовать том</a><a class="button" href="Reed.html">Все тома</a></div></div></section><section class="content" id="materials"><header class="section-head"><p class="eyebrow">Материалы Тома II</p><h2>Одиннадцать свидетельств</h2><p>Открытые материалы основаны только на подтверждённом каноне. Остальные разделы уже имеют собственные страницы и будут дополнены по мере разработки.</p></header><div class="chapter-grid">${sections.map(s=>`<article class="chapter ${s[5]?'':'dev'}" style="--image:url('${s[4]}')"><a href="${s[3]}"><span class="chapter-index">${s[0]}</span><div><p class="chapter-status">${s[5]?'Раздел открыт':'В разработке'}</p><h3>${s[1]}</h3><p>${s[2]}</p></div></a></article>`).join('')}</div><aside class="tome-note"><h2>Преимущественно пустынный мир</h2><p>Турунг-гарх — планета, на которой происходят события Тома II. На ней существуют и другие природные зоны, но пустынные территории определяют основной образ этого мира.</p></aside></section></main>`+footer();nav()};
const boot=async()=>{try{if(!window.TODMAuth)await new Promise((res,rej)=>{addEventListener('todm-auth-ready',res,{once:true});setTimeout(()=>rej(new Error('timeout')),10000)});const a=await TODMAuth.getAccount();if(!a.session)return gate('guest');if(!a.access||a.access.is_banned||!(a.access.full_access||Number(a.access.archive_level)>=3))return gate('level');render()}catch(e){console.error(e);fail()}};boot();})();
